maintainer       "Scalr Inc."
maintainer_email "stunko@scalr.com"
name             "revizor-chef"
license          "All rights reserved"
description      "Cookbook for verifying chef-solo in Scalr"
version          "0.1.0"
