name             'medium-chef'
maintainer       'Scalr Inc.'
maintainer_email 'n.kalmikov@scalr.com'
license          'All rights reserved'
description      'Recipe for medium chef tests'
version          '0.1.0'
