maintainer       "Scalr Inc."
maintainer_email "oleg@scalr.com"
name		     "set_hostname_attr"
license          "All rights reserved"
description      "Cookbook to verify the hostname installed through the cookbooks"
version          "0.1.0"
