name             'print-gv-solo'
maintainer       'Scalr Inc.'
maintainer_email 's.dubrovskyi@scalr.com'
license          'All rights reserved'
description      'Cookbook for print ENV in chef solo'
version          '0.1.0'
